### ISSUE TITLE
Can't run parallel PSRA job at NCI

### ISSUE THREAD

**Issue by dynaryu** [GeoscienceAustralia/eqrm#146]
I ran a PSRA run using mmi based vulnerability. I ran the same code at my mac without any problem.
But when I ran at NCI with parallel process, I got the following error message.

[hxr547@raijin6 code]$ cat setdata_psra_mm.o3261404 
Logfile is '/home/547/hxr547/Projects/scenario_Sydney/prob_risk/log-1.txt' with logging level of WARNING, console logging level is WARNING
Logfile is '/home/547/hxr547/Projects/scenario_Sydney/prob_risk/log-2.txt' with logging level of WARNING, console logging level is WARNING
Logfile is '/home/547/hxr547/Projects/scenario_Sydney/prob_risk/log-3.txt' with logging level of WARNING, console logging level is WARNING
Logfile is '/home/547/hxr547/Projects/scenario_Sydney/prob_risk/log-1.txt' with logging level of WARNING, console logging level is WARNING
Logfile is '/home/547/hxr547/Projects/scenario_Sydney/prob_risk/log-0.txt' with logging level of DEBUG, console logging level is INFO
JS_N{"parallel size": 4}
JS_N{"host name": "r37"}
JS_N{"system platform": "linux2"}
Logfile is '/home/547/hxr547/Projects/scenario_Sydney/prob_risk/log-3.txt' with logging level of WARNING, console logging level is WARNING
Logfile is '/home/547/hxr547/Projects/scenario_Sydney/prob_risk/log-2.txt' with logging level of WARNING, console logging level is WARNING
JS_N{"SVN modified": null, "SVN version": "exported", "SVN date": null}
event_set_handler = generate
P0: Generating event set
Using file /home/547/hxr547/Projects/scenario_Sydney/input/sydney_soil_event_control.xml for event_type source
Using file /home/547/hxr547/Projects/scenario_Sydney/input/sydney_soil_zone_source.xml for zone source
JS_N{"len_source_zones": 2}
P0: Saving event set to /home/547/hxr547/Projects/scenario_Sydney/prob_risk/sydney_soil_event_set
P0: Event set created. Number of events=453209
JS_N{"len_events": 453209}
P0: Sites set created. Number of sites=4
JS_N{"len_max_GMPEs": 3}
JS_N{"len_recurrence_models": 1}
JS*N{"pseudo_events": 1359627}

Traceback (most recent call last):
  File "/home/547/hxr547/Projects/scenario_Sydney/code/setdata_psra_mmi.py", line 87, in <module>
    main(locals())
  File "/home/547/hxr547/Projects/eqrm/eqrm_code/analysis.py", line 238, in main
    all_sites = all_sites[parallel.calc_indices(num_sites)]
  File "/home/547/hxr547/Projects/eqrm/eqrm_code/structures_vulnerability.py", line 209, in **getitem**
    vulnerability_set = copy.deepcopy(self.vulnerability_set)
  File "/apps/python/2.7.6/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/apps/python/2.7.6/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/apps/python/2.7.6/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/apps/python/2.7.6/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/apps/python/2.7.6/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/apps/python/2.7.6/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/apps/python/2.7.6/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/apps/python/2.7.6/lib/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/apps/python/2.7.6/lib/python2.7/site-packages/numpy/core/__init__.py", line 56, in _ufunc_reconstruct
    return getattr(mod, name)
AttributeError: 'module' object has no attribute 'exp'
# 

```
        Resource Usage on 2015-11-13 22:05:24.541629:
JobId: 3261404.r-man2  
Project: y57 
Exit Status: 1 (Linux Signal 1)
Service Units: 0.06
NCPUs Requested: 4              NCPUs Used: 4
                        CPU Time Used: 00:01:30
Memory Requested: 4gb               Memory Used: 1gb
                        Vmem Used: 2gb
Walltime requested: 01:00:00            Walltime Used: 00:00:52
jobfs request: 2048mb               jobfs used: 1mb
```
#

**Comment by basaks** [comment]
Hi Hyeuk,

I created a virtualenv with these:

```
Shapely==1.5.13
numpy==1.10.1
scipy==0.16.1
wsgiref==0.1.2
```

Then I used `python setdata_psra_mmi.py`. The code ran just fine.

**Comment by dunkgray** [comment]
This isn't code which is part of the EQRM repo, and it is running for Hyeuk and Sudipta. Closing the ticket.
